### ISSUE TITLE
Fibonacci Series

### ISSUE THREAD

**Issue by mbakrol** [mbakrol/MB-Hacktoberfest2021#1]
### *Description*

Write a Java Program to to create a fibonacci series

Before doing PR go through the below mentions 

[Contribution Guideline](https://github.com/mbakrol/MB-Hacktoberfest2021/blob/main/CONTRIBUTING.md),

To get PR reviewed faster tag me (mbakrol)

**Comment by Onkar627** [comment]
@mbakrol I could work on this issue as well :)

**Comment by AB-Jeet** [comment]
May I work on this ??

**Comment by vilgad** [comment]
can i work on this issue as my first contribution?

**Comment by Niyati3031** [comment]
Can you assign this to me please @mbakrol

**Comment by pavitrapati** [comment]
I would like to work on this issue with utmost sincerity. Please assign this issue to me.
@mbakrol

**Comment by anupamdey2001** [comment]
Please Can you assign this to me @mbakrol
