### ISSUE TITLE
Fizz buzz problem

### ISSUE THREAD

**Issue by mbakrol** [mbakrol/MB-Hacktoberfest2021#2]
### Description

Write a Java Program to solve fizz buzz problem.

Before doing PR go through the below mentions 

[Contribution Guideline](https://github.com/mbakrol/MB-Hacktoberfest2021/blob/main/CONTRIBUTING.md),

To get PR reviewed faster tag me (mbakrol)

**Comment by Krupali-Tandel** [comment]
@mbakrol  Assign me this issue

**Comment by AB-Jeet** [comment]
Can you pls assign it to me ??

**Comment by ayushsaxena119** [comment]
Assign this issue to me.

**Comment by AB-Jeet** [comment]
Thanks for assigning me.

**Comment by prahasR** [comment]
Hi @mbakrol, if the problem is open now, I am ready to contribute , please assign

**Comment by Niyati3031** [comment]
Can you please assign this to me @mbakrol its my first time with github please help me to contribute

**Comment by pavitrapati** [comment]
I would like to work on this issue with utmost sincerity. Please assign this issue to me.
@mbakrol
