### ISSUE TITLE
Leap Year Problem

### ISSUE THREAD

**Issue by mbakrol** [mbakrol/MB-Hacktoberfest2021#4]
### Description

Write a Java Program to Solve leap year probelm

Before doing PR go through the below mentions 

[Contribution Guideline](https://github.com/mbakrol/MB-Hacktoberfest2021/blob/main/CONTRIBUTING.md),

To get PR reviewed faster tag me (mbakrol)

**Comment by Krupali-Tandel** [comment]
@mbakrol  I want to work in this issue

**Comment by ParthPali** [comment]
Hello @mbakrol, can you please assign this issue to me
