### ISSUE TITLE
Linear Search Algo

### ISSUE THREAD

**Issue by mbakrol** [mbakrol/MB-Hacktoberfest2021#5]
### Description

Write a Java Program to Implement Linear Search Algorithm.

Before doing PR go through the below mentions 

[Contribution Guideline](https://github.com/mbakrol/MB-Hacktoberfest2021/blob/main/CONTRIBUTING.md),

To get PR reviewed faster tag me (mbakrol)

**Comment by Onkar627** [comment]
@mbakrol I want to work on this issue.Please assign it to me:)

**Comment by DVB7781** [comment]
kindly assign this to me

**Comment by prahasR** [comment]
@mbakrol I also want to contribute to this.

**Comment by rsarthak** [comment]
@mbakrol  I have create a PR, kindly review it #50

**Comment by Niyati3031** [comment]
Can you assign this to me please @mbakrol

**Comment by pavitrapati** [comment]
I would like to work on this issue with utmost sincerity. Please assign this issue to me.
@mbakrol
