### ISSUE TITLE
Even _odd

### ISSUE THREAD

**Issue by mbakrol** [mbakrol/MB-Hacktoberfest2021#55]
### *Description*

Write a Java Program to solve even odd problem

Before doing PR go through the below mentions 

[Contribution Guideline](https://github.com/mbakrol/MB-Hacktoberfest2021/blob/main/CONTRIBUTING.md),

To get PR reviewed faster tag me (@mbakrol)

**Comment by viralkumar28** [comment]
hey can you assign this to me, i want to contribute.

**Comment by ashusharma-cs** [comment]
Hello there, would you please like to assign this to me?

**Comment by mbakrol** [comment]
@ashusharma-cs assigned to you

**Comment by ashusharma-cs** [comment]
Please assign this to me

**Comment by ashusharma-cs** [comment]
Thankyou @mbakrol

**Comment by Rimjhim20** [comment]
@mbakrol  assigned it to me.

**Comment by prog-harsh** [comment]
@mbakrol please assign it to me.

**Comment by malvika-sinha** [comment]
@mbakrol Kindly assign me for this task.
