### ISSUE TITLE
Math methods

### ISSUE THREAD

**Issue by mbakrol** [mbakrol/MB-Hacktoberfest2021#6]
### Description

Write a Java Program to demonstrate common math methods used.

Before doing PR go through the below mentions 

[Contribution Guideline](https://github.com/mbakrol/MB-Hacktoberfest2021/blob/main/CONTRIBUTING.md),

To get PR reviewed faster tag me (mbakrol)

**Comment by rjkalash** [comment]
hey , can you assign this task to me

**Comment by ParthPali** [comment]
Hey @mbakrol can you assign this task to me
