### ISSUE TITLE
Meter to feet

### ISSUE THREAD

**Issue by mbakrol** [mbakrol/MB-Hacktoberfest2021#7]
### Description

Write a Java Program to convert meter into feet.

Before doing PR go through the below mentions 

[Contribution Guideline](https://github.com/mbakrol/MB-Hacktoberfest2021/blob/main/CONTRIBUTING.md),

To get PR reviewed faster tag me (mbakrol)

**Comment by DVB7781** [comment]
Kindly assign this issue to me :)

**Comment by ayushsaxena119** [comment]
Please assign this issue to me.
