### ISSUE TITLE
GCD 

### ISSUE THREAD

**Issue by mbakrol** [mbakrol/MB-Hacktoberfest2021#8]
### Description

Write a Java Program to Find GCD of two numbers

Before doing PR go through the below mentions 

[Contribution Guideline](https://github.com/mbakrol/MB-Hacktoberfest2021/blob/main/CONTRIBUTING.md),

To get PR reviewed faster tag me (mbakrol)

**Comment by AnandDasani2670** [comment]
@mbakrol I want to work on this issue

**Comment by AnandDasani2670** [comment]
@mbakrol  assing this isse to me

**Comment by Niyati3031** [comment]
Can you assign this to me please @mbakrol
